# 开发环境配置
app:
    prefix: ''
    port: 8088
    logger:
        # 项目日志存储路径，相对路径（相对本项目根目录）或绝对路径
        dir: '../logs'
    # 文件相关
    file:
        # 是否为本地文件服务或cos
        isLocal: false
        # location 文件上传后存储目录，相对路径（相对本项目根目录）或绝对路径
        location: '../upload'
        # 文件服务器地址，这是开发环境的配置 生产环境请自行配置成可访问域名
        domain: 'http://localhost:9000'
        # 文件虚拟路径, 必须以 / 开头， 如 http://localhost:8080/profile/****.jpg  , 如果不需要则 设置 ''
        serveRoot: '/profile'
        # 文件大小限制，单位M
        maxSize: 10
